### ISSUE TITLE
M2

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#1]
## Task Details

- [x] Install git
- [x] Download and unzip the M2.zip, and import as a new project
- [x] Clone out the project M2
- [x] Follow the directions in the M2 wiki page on tsquare to edit and commit files
- [x] Follow the directions to add and remove files
- [x] Follow the directions on building files with gradle

## Done Done Criteria
Each team member understands the basics of git, as well as how to write a build file using gradle.
