### ISSUE TITLE
M7 - Google Maps

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#10]
## Task Details
- [x] Implement way to navigate to water availability screen
- [x] Display the map
- [x] Implement placing pins on the map
- [x] Implement showing report details when a pin is clicked

## Done Done Criteria
- [x] Previous features still work
- [x] Navigation to water availability 
- [x] Map displays
- [x] Pins exist on map at report locations
- [x] Selecting a pin shows report details
- [x] Javadocs
