### ISSUE TITLE
M8 - Purity Report

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#11]
## Task Details
- [x] Implement water quality report screen
- [x] Add a submit button that adds a water quality report
- [x] Add a cancel button that does not add a water quality report
- [x] Implement manager functionality to view a list of water quality reports

## Done Done Criteria
- [x] Able to navigate to water quality report screen
- [x] Users are not able to access water quality report screen
- [x] Submit/cancel buttons have appropriate functionality
- [x] Submit button adds water quality report to Model
- [x] Manager can view list of water quality reports
- [x] Javadocs
