### ISSUE TITLE
M9 - Persistence

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#12]
## Task Details
- [x] Implement a way to save the data
- [x] Implement loading of saved data
- [x] Provide option to save and load system data

## Done Done Criteria
- [x] Data can be saved
- [x] Data can be loaded
- [x] Previous functionality still works
- [x] Javadocs
