### ISSUE TITLE
M9 - History Graph

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#13]
## Task Details
- [x] Implement a way manager can see the option to view the historical purity report
- [x] Create a prompt to ask the manager for information in order to create the report
- [x] Implement the display of an XY graph with appropriate information

## Done Done Criteria
- [x] Managers only can request a historical report
- [x] Managers can enter setup information for the graph
- [x] Graph displays appropriately
- [x] Javadocs
