### ISSUE TITLE
M3

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#2]
## Task Details

- [ ] Download and extract the M3.zip file from tsquare into your IDE directory
- [ ] Follow the directions to make changes to the model
- [ ] Follow the directions to make changes to the view
- [ ] Follow the directions to make changes to the controller
- [ ] Run the application to ensure correct implementation
- [ ] Zip the project directory and submit on tsquare

## Done Done Criteria
Each team member understands how to build and execute an Android application, and the pre-written code has been edited in order to supplement team members' knowledge of MVC.
