### ISSUE TITLE
M4

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#3]
## Task Details

- [x] Create a Context Diagram for the system
- [x] Think of and list 10 user stories
- [x] Choose a user story for each team member to elaborate
- [x] Create and Import the team Android Project
- [x] Create a screen with options for Login and Registration
- [x] Implement specified functionality when a user selects an option
- [x] Implement a logout feature
- [x] Combine and submit the team's User Stories in one .pdf file (one person)

## Done Done Criteria
Login/logout functionality has been added to the project, and user stories are correctly formatted.
