### ISSUE TITLE
M5 - UML Diagram

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#4]
## Task Details
- [x] Brainstorm candidate classes/objects
- [x] Filter out unnecessary classes/objects
- [x] List any attributes and stereotypes
- [x] Write down interactions between classes
- [x] Show multiplicity requirements

## Done Done Criteria
- [x] Model contains appropriate classes
- [x] Classes annotated with appropriate stereotypes
- [x] Model contains appropriate interactions
- [x] Model shows multiplicity
- [x] Model contains appropriate attributes
