### ISSUE TITLE
M5 - User Registration

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#5]
## Task Details
- [x] Add a registration screen
- [x] Add functionality to add user to system upon registration acceptance
- [x] Add functionality to not add user if registration is cancelled
- [x] Allow user to designate their account type during registration

## Done Done Criteria
- [x] User registration screen integrated
- [x] Accepted registration adds user to the system
- [x] Cancelled registration does not add user to the system
- [x] Backend user list created/updates
- [x] User can select account type
- [x] Javadocs
