### ISSUE TITLE
M5 - User Profile

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#6]
## Task Details
- [x] Add a user profile screen
- [x] Add edit functionality, along with associated confirm/cancel editing capabilities

## Done Done Criteria
- [x] User can create a profile with email address, home address, title, etc.
- [x] User can edit these fields
- [x] Javadocs
