### ISSUE TITLE
M6 - Diagrams

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#7]
## Task Details
- [x] Create individual robustness diagram from each person's chosen story from M4
- [x] Create an architecture diagram displaying the chosen architecture of the system
- [x] Annotate the architecture diagram with trust boundaries
- [x] Create a UI flow diagram showing the screens of the application
- [x] Develop a prototype of the screens in the app (Fluid UI is acceptable)

## Done Done Criteria
- [x] Individual robustness diagrams created
- [x] Architecture diagram created
- [x] UI flow diagram created
- [x] Prototype created
