### ISSUE TITLE
M6 - User Water Report

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#8]
## Task Details
- [x] Implement way to navigate to water report submission screen
- [x] Implement screen for inputting water reports
- [x] Create submit/cancel buttons on this screen
- [x] Implement logic to add submitted reports to a list of water reports
- [x] Create logic to auto assign water report number

## Done Done Criteria
- [x] Login/Registration/Profile still works
- [x] Can navigate to report submission screen
- [x] Submitted reports are stored in model
- [x] List of reports can be viewed
- [x] Javadocs
