### ISSUE TITLE
M7 - UML Class Diagram

### ISSUE THREAD

**Issue by MLord8** [MLord8/water-reporter#9]
## Task Details
- [x] Show implementation of model classes
- [x] Label regular associations
- [x] Mark collaborations
- [x] Format methods and attributes

## Done Done Criteria
- [x] Regular associations have labels
- [x] Multiplicity shown
- [x] Class names singular unless collection
- [x] Attribute/method formats
- [x] Appropriate use of inheritance
- [x] Class identification appropriate
- [x] Collaborations appropriate
